# -*- coding: utf-8 -*-
BASLIK = ("KUYRUĞA OTURAN, KANAT-GÖVDE BİÇİMLİ, KUMANDA YÜZEYİ BULUNMAYAN "
          "İNSANSIZ HAVA ARACI VE BUNA AİT YUVARLANMA KUMANDA DÜZENEĞİ")

# (baslik_tipi, metin)  -> h2 / h3 / p / f (formul) / tbl
TARIFNAME = [
("h2","TEKNİK ALAN"),
("p","Buluş, dikey olarak kalkıp inebilen ve seyir uçuşunu kanat üzerinde gerçekleştiren insansız hava araçları ile ilgilidir."),
("p","Buluş özellikle, gövdesi boyuna ekseni dikey konumda yere oturan (kuyruğa oturan) tipteki, kanat ile gövdesi bütünleşik (kanat-gövde) yapıda olan ve klasik anlamda hareketli kumanda yüzeyi (elevon, kanatçık, dümen) taşımayan bir hava aracına ve bu hava aracında yuvarlanma momenti üretmeye yarayan bir düzeneğe ilişkindir."),

("h2","TEKNİĞİN BİLİNEN DURUMU"),
("p","Dikey kalkış ve iniş yapabilen, aynı zamanda kanat üzerinde verimli seyir uçuşu gerçekleştirebilen hava aracı arayışı yetmiş yılı aşkın süredir devam etmektedir."),
("p","Kuyruğa oturan hava araçları bilinmektedir. Bu düzenlemede, seyirde kullanılan itki organı aynı zamanda dikey kalkışı da sağladığından, araç ayrıca bir kaldırma sistemi taşımaz."),
("p","Kanat ile gövdenin bütünleştiği kanat-gövde biçimli hava araçları bilinmektedir; kuyruğa oturan insansız hava araçlarında kuyruksuz kanat-gövde düzenlemesi yaygındır."),
("p","Koaksiyel karşıt dönüşlü pervane çiftleri bilinmektedir. Bu düzenlemede ortak eksen üzerinde ters yönde dönen iki pervane, birbirinin tepki torkunu dengeleyerek gövdeye net tepki torku aktarmaz."),
("p","Seri hibrit güç aktarma organları bilinmektedir; içten yanmalı bir motor bir jeneratörü, jeneratör de elektrik motorlarını besler."),
("p","Hareketli kumanda yüzeyi bulunmayan, yalnızca motor itki farkıyla kumanda edilen kuyruğa oturan hava araçları da bilinmektedir. Bu bilinen çözümlerde, koaksiyel olmayan dört adet tek pervane açıklık boyunca dağıtılmış hâlde bulunmaktadır."),
("p","Gövde boyuna eksenine paralel itki üreten pervanelerden oluşan bir düzende, bir pervanenin ürettiği kuvvet F = (Fx, 0, 0) ve bu kuvvetin uygulama noktası r = (x, y, z) olmak üzere, boyuna eksen etrafındaki moment"),
("f","Mx = y · Fz − z · Fy = 0"),
("p","bağıntısıyla verilmekte olup özdeş olarak sıfırdır. Pervanelerin sayısı ve konumu ne olursa olsun, itki vektörleri gövde eksenine paralel kaldığı sürece yuvarlanma momenti üretilemez."),
("p","Bilinen kumanda yüzeysiz çözümler bu durumu, pervanelerin diferansiyel tepki torkundan yararlanarak aşmaktadır: ters yönde dönen tek pervanelerin devir sayıları farklılaştırılarak gövdeye net bir tepki torku aktarılmakta ve bu tork yuvarlanma momenti olarak kullanılmaktadır."),
("p","Ancak bu çözüm, koaksiyel karşıt dönüşlü pervane çiftleri kullanan bir hava aracında uygulanamaz. Koaksiyel çiftin varlık sebebi tepki torkunu ortadan kaldırmaktır; tepki torku ortadan kalktığında, bilinen çözümün yuvarlanma aktüatörü de ortadan kalkmaktadır. Bu iki tercih birbirini dışlamaktadır."),
("p","Alternatif olarak, pervane izine hareketli kumanda yüzeyi yerleştiren çözümler bilinmektedir. Bu çözümler, kumanda yüzeyi taşımamanın sağladığı üstünlüklerden vazgeçmek zorundadır."),

("h2","BULUŞUN ÇÖZÜMÜNÜ AMAÇLADIĞI TEKNİK PROBLEM"),
("p","Buluşun amacı, koaksiyel karşıt dönüşlü pervane çiftleriyle donatılmış, kuyruğa oturan, kanat-gövde biçimli bir hava aracında, tepki torkunun tasarım gereği ortadan kaldırılmış olmasına rağmen, hareketli bir kumanda yüzeyi kullanılmaksızın, hem hava hızının sıfır olduğu askı hâlinde hem de seyir uçuşunda yuvarlanma momenti üretebilen bir düzenek sağlamaktır."),
("p","Buluşun bir diğer amacı, itki organlarının açıklık boyunca dağıtılmasına gerek kalmaksızın, tek bir merkezî itki organıyla hem dikey kalkışın hem de seyir itkisinin sağlanmasıdır."),

("h2","BULUŞUN AÇIKLAMASI"),
("p","Buluş, gövdesi (1) kanat-gövde biçiminde olan, boyuna ekseni dikey konumda yere oturan bir insansız hava aracıdır."),
("p","Aracın tüm itki gücü, gövdenin (1) burun ucunda bulunan tek bir koaksiyel karşıt dönüşlü pervane çifti (2) tarafından üretilir. Bu çift; dikey kalkışta, askıda, geçişte ve seyirde aynı organ olarak ve gövdeye göre aynı yönelimde çalışır. Eğilmez, döndürülmez, katlanmaz ve içeri çekilmez. İtki organı açıklık boyunca dağıtılmamıştır."),
("p","Kanat uçlarında, planform düzlemine dik olarak yukarı ve aşağı uzanan uç iskeletleri (3) bulunur. Bu iskeletlerin uçlarında, yalnızca yönelim momenti üretmeye hizmet eden dört adet küçük koaksiyel karşıt dönüşlü pervane çifti (4) yer alır. Söz konusu çiftler kaldırmaya katkı vermez ve askı gücünün küçük bir bölümünü çeker."),
("p","Gövdenin (1) alt yüzeyinde, burun bölgesine yakın bir noktadan başlayarak planform düzleminde gövde eksenine göre açılı biçimde arkaya ve dışa doğru uzanan, açılıp kapanan bir yuvarlanma şeridi (5) bulunur. Şerit açıldığında alt yüzeyden dışarı çıkarak akışa engel oluşturur, kapandığında yüzeyle bütünleşir."),
("p","Şeridin (5) belirleyici özelliği, iç kısmının burun pervane çiftinin (2) izi (13) içinde kalmasıdır. Pervane izindeki dinamik basınç"),
("f","q = T / A"),
("p","bağıntısıyla verilir; burada T itki, A ise pervane disk alanıdır. Bu büyüklük disk yüklemesine eşit olup serbest akış hızından bağımsızdır. Bu nedenle şerit, hava hızı sıfır iken dahi, yani araç askıda dururken de moment üretir."),
("p","Şeridin (5) dış kısmı pervane izinin (13) dışında kalır ve seyir uçuşunda serbest akışa karşı çalışarak yuvarlanma momenti üretir. Böylece tek bir organ iki uçuş rejimine birden hizmet eder: iç kısmı askıda, dış kısmı seyirde."),
("p","Şerit (5) oransal bir kumanda yüzeyi değildir; sürekli değişen bir açıya sahip olmayıp yalnızca açık ve kapalı konumları bulunur. Bu yönüyle pervane izine yerleştirilen kumanda yüzeyi çözümlerinden ayrılır."),
("p","Aracın enerji sistemi seri hibrit düzendedir: yakıt deposundan (11) beslenen içten yanmalı motor (7) bir jeneratörü (8) döndürür; jeneratör (8), pervane çiftlerini süren elektrik motorlarını (10) besler. Askı anındaki güç tepesi bir pil tamponundan (9) karşılanır. Motor (7) hiçbir pervaneye mekanik olarak bağlı değildir; bu sayede motor askı gücüne göre değil seyir gücüne göre boyutlandırılır ve karşıt dönüşlü dişli kutusu hiç oluşmaz."),
("p","Araç beş noktadan yere oturur: uç iskeletlerinin (3) dört alt ucu ve gövdenin (1) firar kenarından geriye uzanan orta omurganın (6) arka ucu."),
("h3","Buluşun sağladığı üstünlükler"),
("p","Hareketli kumanda yüzeyi bulunmadığından servo, bağlantı çubuğu ve ilgili yapı taşınmaz; kumanda otoritesi tutukluk açısının üstünde yitirilmez."),
("p","Tepki torku koaksiyel çiftlerle giderildiğinden, torku sürekli dengeleyecek ayrı bir organa gerek kalmaz."),
("p","İtki organı açıklığa dağıtılmadığından, seyirde akışa maruz kalan kaldırma donanımı bulunmaz."),
("p","Şerit (5) tek organ olarak iki rejime birden hizmet ettiğinden, askı ve seyir için ayrı kumanda organları gerekmez."),
("p","Koaksiyel çiftlerin net açısal momentumu sıfır olduğundan, dikey uçuştan yatay uçuşa geçiş sırasında jiroskopik moment doğmaz."),

("h2","ŞEKİLLERİN AÇIKLAMASI"),
("p","Şekil 1 — Hava aracının perspektif görünüşü."),
("p","Şekil 2 — Hava aracının üstten görünüşü."),
("p","Şekil 3 — Hava aracının önden görünüşü."),
("p","Şekil 4 — Hava aracının alttan görünüşü; yuvarlanma şeridi (5) ve burun pervane çiftinin izi (13) gösterilmiştir."),
("p","Şekil 5 — Seri hibrit güç akış şeması."),
("h3","Şekillerdeki referans numaraları"),
("tbl",[("1","Gövde (kanat-gövde)"),("2","Burun koaksiyel karşıt dönüşlü pervane çifti"),
        ("2a","Ön pervane"),("2b","Arka pervane"),("3","Uç iskeleti"),("3a","Üst dikme"),
        ("3b","Alt dikme"),("4","Uç koaksiyel pervane çifti"),("5","Yuvarlanma şeridi"),
        ("6","Orta omurga"),("7","İçten yanmalı motor"),("8","Jeneratör"),
        ("9","Pil tamponu"),("10","Elektrik motoru"),("11","Yakıt deposu"),
        ("12","Faydalı yük hacmi"),("13","Burun pervane çiftinin izi")]),

("h2","BULUŞUN DETAYLI AÇIKLAMASI"),
("h3","Gövde (1)"),
("p","Gövde (1), burun ucundan firar kenarına kadar kesiti kanat profili biçiminde olan, ayrı bir silindirik gövde taşımayan kanat-gövde yapısındadır. Faydalı yük (12), gövde içinde, taşıma üreten hacmin içinde taşınır."),
("p","Gövdenin (1) hücum kenarı ok açısı kökten uca doğru azalarak değişir; firar kenarı ok açısı sabittir. Kalınlık oranı kökten uca azalır. Bir uygulama biçiminde hücum kenarı ok açısı kökte yaklaşık 45 derece, uçta yaklaşık 38 derecedir; firar kenarı ok açısı yaklaşık 25 derecedir; kalınlık oranı kökte yaklaşık yüzde 25, uçta yaklaşık yüzde 12'dir."),
("p","Kuyruksuz düzenleme nedeniyle yunuslama dengesi, ok açısı dağılımı ve profil refleksi ile sağlanır; ayrı bir yatay stabilizatör bulunmaz."),
("h3","Burun pervane çifti (2)"),
("p","Burun pervane çifti (2), ortak eksen üzerinde ters yönlerde dönen iki pervaneden (2a, 2b) oluşur. Her pervane kendi elektrik motoruyla (10) sürüldüğünden, iki pervane arasında mekanik dişli bağlantısı bulunmaz."),
("p","Pervaneler sabit geometrilidir; devirli hatve ve toplu hatve düzenekleri bulunmaz. Çiftin iki pervanesi farklı sabit burulma açısına sahip olabilir."),
("p","Tam tork dengesi tek bir çalışma noktasında kurulur. Bir uygulama biçiminde bu nokta seyir olarak seçilir; askıda kalan küçük artık tork, yuvarlanma şeridiyle (5) dengelenir."),
("h3","Uç iskeletleri (3) ve uç pervane çiftleri (4)"),
("p","Uç iskeletleri (3), kanat ucundan planform düzlemine dik olarak yukarı (3a) ve aşağı (3b) uzanır. Uzama miktarı, bir uygulama biçiminde yerel uç veterinin yaklaşık üç katıdır."),
("p","Uç iskeletleri (3) üç işlevi birlikte görür: uç pervane çiftlerinin (4) bağlantı yapısıdır, kumanda momenti kolunu oluşturur ve yere oturma yapısıdır."),
("p","Kumanda momenti M = 2 · T · L bağıntısıyla verildiğinden, kolun uzatılması aynı momentin daha küçük itkiyle üretilmesini sağlar. Pervane gücü itkinin üç bölü iki kuvvetiyle değiştiğinden, kolun uzatılması gereken gücü belirgin biçimde azaltır. Kolun uzaması aynı zamanda yere oturma tabanını genişletir."),
("p","Uç pervane çiftlerinden (4) üst ve alt olanlar arasındaki itki farkı bir yanal eksen etrafında, sol ve sağ olanlar arasındaki itki farkı ise diğer yanal eksen etrafında moment üretir. Araç yatay uçuşa geçtiğinde aynı dört organ aynı iki ekseni, rolleri değişerek kumanda etmeye devam eder; hiçbir organ işlevini, yönelimini veya bağlantısını değiştirmez."),
("p","Uç pervane çiftleri (4) kaldırmaya değil yalnızca kumandaya boyutlandırılır. Bir uygulama biçiminde bu çiftlerin toplam güç talebi, askı gücünün yüzde 15'inden azdır."),
("h3","Yuvarlanma şeridi (5)"),
("p","Şerit (5), gövdenin (1) alt yüzeyinde, burun ucundan kök veterinin yaklaşık yüzde 15'i kadar geride başlar ve planform düzleminde açıklık ile veter yönlerinde eşit hızda ilerleyerek yaklaşık 45 derecelik bir yol izler."),
("p","Şeridin planformdaki uzunluğu, bir uygulama biçiminde kök veterinin en az yüzde 100'ü, tercihen yaklaşık yüzde 120'sidir. Dış ucu yarı açıklığın yaklaşık üçte ikisine ulaşır."),
("p","Şeridin açıldığındaki yüksekliği iç uçtan dış uca doğru artar; bir uygulama biçiminde iç uçta yaklaşık 2 santimetre, dış uçta yaklaşık 6 santimetredir. Yükseklik, yerel veterin küçük bir oranında kalacak biçimde sınırlanır; aksi hâlde şerit hava freni gibi davranır."),
("p","Şeridin ürettiği moment esas olarak boyundan kaynaklanır; yüksekliğin artırılmasının getirisi doyuma girer."),
("p","Bir uygulama biçiminde, burun pervane çiftinin (2) izi (13) yarı açıklığın yaklaşık yüzde 27 ile yüzde 39'u arasındaki bölgeyi kaplar ve şeridin (5) yaklaşık iç yarısı bu bölge içinde kalır. Böylece şeridin iç kısmı askıda, dış kısmı seyirde etkindir."),
("p","Şerit (5) simetrik olarak iki yarıda bulunur; yuvarlanma momenti, bir yarının açılıp diğerinin kapalı kalmasıyla üretilir."),
("h3","Enerji sistemi"),
("p","Yakıt deposundan (11) beslenen içten yanmalı motor (7), jeneratörü (8) döndürür. Jeneratör (8), pervane çiftlerini (2, 4) süren elektrik motorlarını (10) besler. Pil tamponu (9), askı ve geçiş anlarındaki güç tepesini karşılar."),
("p","Bir uygulama biçiminde pil tamponunun (9) kütlesi, azami kalkış kütlesinin yüzde 5'inden az olup motor (7) askı gücünün üçte birinden küçük bir güce göre boyutlandırılır."),
("h3","Uçuş profili"),
("p","Araç beş noktadan yere oturur. Burun pervane çifti (2) ağırlığı aşan itkiye ulaştığında araç dikey olarak yükselir; yönelim uç pervane çiftleriyle (4) korunur."),
("p","Dikey uçuştan yatay uçuşa geçiş, aracın tırmanışı kesilmeden başlatılır. Giriş anındaki tırmanış hızı, dönüş süresince harcanacak bir dikey momentum rezervi oluşturur. Dönüş hızlı değil yavaş yapılır; dönüş süresi uzadıkça gövde ekseninin dikeyle yaptığı açının kosinüsü daha uzun süre büyük kalır ve bu sürede kanat taşıma üretmeye başlar."),
("p","Seyirde burun pervane çifti (2) seyir itkisini üretir; yunuslama ve yönelme uç çiftleriyle (4), yuvarlanma ise şeritle (5) sağlanır."),
("p","İniş, geçişin tersidir; araç yavaşlar, burnu yukarı döner ve beş temas noktası üzerine dikey olarak iner. Yerden yükseklik, insan gözlemine değil sensör ölçümüne dayanır."),
("h3","Ölçeklenebilirlik"),
("p","Aynı düzenleme farklı azami kalkış kütlelerinde uygulanabilir. Askı gücünün kütleyle birlikte aşırı büyümesini önlemek için disk yüklemesi sabit tutulur; bunun için disk alanı kütleyle orantılı olarak büyütülür. Disk alanı, pervane çapının artırılmasıyla veya koaksiyel çift sayısının artırılmasıyla büyütülür. Her çift kendi içinde tork dengeli olduğundan, çift eklemek düzenlemeyi bozmaz."),
("p","Ölçek büyüdükçe geçiş dönüşü yavaşlar; gereken moment M = I · α bağıntısı ve atalet momentinin kütle ile uzunluğun karesi çarpımıyla orantılı olması nedeniyle ölçekle hızla büyür."),
]
